[package]
name = "praxis_graphics"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
bytemuck = { version = "1.23.1", features = ["derive"] }
pollster = "0.4.0"
raw-window-handle = "0.6.2"
winit = { version = "0.30.11", features = ["rwh_05"] }
praxis_utils = { path = "../praxis_utils", version = "0.1.0" }
praxis_math = { path = "../praxis_math", version = "0.1.0" }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
