[package]
name = "praxis_procedural"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
praxis_utils = { path = "../praxis_utils", version = "0.1.0" }
praxis_math = { path = "../praxis_math", version = "0.1.0" }
bytemuck = { version = "1.23.1", features = ["derive"] }
rand = "0.8"
seahash = "4.1"
