[package]
name = "praxis_scene"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
praxis_ecs = { path = "../praxis_ecs", version = "0.1.0" }
praxis_math = { path = "../praxis_math", version = "0.1.0" }
praxis_utils = { path = "../praxis_utils", version = "0.1.0" }
bevy_ecs = "0.14"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"

[lints]
workspace = true
