[package]
name = "praxis_physics"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rapier3d = "0.22"
praxis_ecs = { path = "../praxis_ecs", version = "0.1.0" }
praxis_math = { path = "../praxis_math", version = "0.1.0" }
praxis_utils = { path = "../praxis_utils", version = "0.1.0" }
bevy_ecs = "0.14"

[lints]
workspace = true
