[package]
name = "praxis_input"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
winit = { version = "0.30.11", features = ["rwh_05"] }
bevy_ecs = "0.14"
praxis_utils = { path = "../praxis_utils", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serialization = ["serde"]

[lints]
workspace = true
