[package]
name = "praxis_assets"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
tobj = "4.0"
gltf = { version = "1.4", features = ["names"] }
praxis_utils = { path = "../praxis_utils", version = "0.1.0" }
praxis_graphics = { path = "../praxis_graphics", version = "0.1.0" }
praxis_math = { path = "../praxis_math", version = "0.1.0" }
praxis_scene = { path = "../praxis_scene", version = "0.1.0" }
