name: Build Everything

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache APT packages
        uses: actions/cache@v4
        id: apt-cache
        with:
          path: |
            /var/cache/apt/archives/*.deb
          key: ${{ runner.os }}-apt-${{ hashFiles('**/build.yml') }}


      - name: Install base dependencies
        if: steps.apt-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential make \
          pkg-config ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev \
          lsb-release

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: latest
          cache: true
        id: vulkan-setup

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: |
            build
            !build/CMakeCache.txt
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure CMake
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          echo "Using Vulkan SDK: $VULKAN_SDK"
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DVulkan_INCLUDE_DIR="$VULKAN_SDK/include" \
            -DVulkan_LIBRARY="$VULKAN_SDK/lib/libvulkan.so"
      

      - name: Build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          cmake --build build --config Release