name: PR Title Check (Conventional Commits)

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Validate PR title (Conventional Commits)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' < $GITHUB_EVENT_PATH)
          if [[ "$PR_TITLE" =~ ^build\(deps(-dev)?\): ]]; then
            # dependabot PRs are allowed to have a different title
            exit 0
          elif [[ ! "$PR_TITLE" =~ ^(chore|docs|feat|fix|refactor|style|test|perf|ci|build|revert)(\(.+\))?(!)?:\ \[[A-Z]+\-([A-Z]+|[0-9]+)\]\ .+ ]]; then
            echo "PR title does not follow Conventional Commits syntax (type: [JRA-123] title)|(type: [NO-JIRA] title): $PR_TITLE"
            exit 1
          fi